[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
projectwho = "AiMmqdacpZ8E2TR76sTfV2ZN34BN1KcnTazEe9gxyA4o"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/nursultanseyhanlioglu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
