[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nur_vault = "HqpHC54qib1S7yHVscMxPH46zBf5VoxXiMGzjr9yAVZf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/nursultanseyhanlioglu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
